server {
    listen 80;
    server_name _;
    root /var/www/ddtown-piano;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Enable aggressive caching for static assets
    location ~* \.(js|css|mp3|mid|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
        access_log off;
    }

    # Custom error pages (optional)
    error_page 404 /index.html;
}
